# tasks file
---
- name: create (download) directory
  ansible.builtin.file:
    path: "{{ ant_downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - ant
    - ant-download

- name: download
  ansible.builtin.get_url:
    url: "https://dlcdn.apache.org/ant/binaries/apache-ant-{{ ant_version }}-bin.tar.gz"
    dest: "{{ ant_downloads_path }}/apache-ant-{{ ant_version }}-bin.tar.gz"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - ant
    - ant-downloads

- name: install
  ansible.builtin.unarchive:
    src: "{{ ant_downloads_path }}/apache-ant-{{ ant_version }}-bin.tar.gz"
    dest: "{{ ant_install_prefix }}"
    creates: "{{ ant_install_prefix }}/apache-ant-{{ ant_version }}"
    copy: false
  tags:
    - configuration
    - ant
    - ant-install

- name: verify
  ansible.builtin.command: >
    {{ ant_install_prefix }}/apache-ant-{{ ant_version }}/bin/ant -version
  changed_when: false
  tags:
    - configuration
    - ant
    - ant-install
    - ant-install-verify
